################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := master
APP_SOURCES := source/master.c

include ../../../runtime/make/exos.mk
