################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2026 Jango73
#
################################################################################

APP_NAME := pipe-source
APP_SOURCES := source/pipe-source.c

include ../../../runtime/make/exos.mk
