################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2026 Jango73
#
################################################################################

APP_NAME := pipe-summary
APP_SOURCES := source/pipe-summary.c

include ../../../runtime/make/exos.mk
