################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := memory-stress
APP_SOURCES := source/memory-stress.c

include ../../../runtime/make/exos.mk
