/************************************************************************\

    EXOS Kernel
    Copyright (c) 1999-2025 Jango73

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.


    Shell - Embedded E0 Scripts

\************************************************************************/

#include "shell/Shell-EmbeddedScripts.h"

/************************************************************************/

static LPCSTR G_EmbeddedScripts[SHELL_EMBEDDED_SCRIPT_COUNT] = {
    [SHELL_EMBEDDED_SCRIPT_DRIVER_LIST] = (LPCSTR)
        "count = driver.count;\n"
        "if (count == 0) {\n"
        "    print(\"No driver detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    alias = driver[i].alias;\n"
        "    if (alias == \"\") {\n"
        "        alias = \"<none>\";\n"
        "    }\n"
        "    product = driver[i].product;\n"
        "    if (product == \"\") {\n"
        "        product = \"<none>\";\n"
        "    }\n"
        "    print(alias + \" type=\" + driver[i].type_name + \" ready=\" + driver[i].ready + \" product=\" + product);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_DRIVER_DETAILS] = (LPCSTR)
        "count = driver.count;\n"
        "found = 0;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (driver[i].alias != target_alias) {\n"
        "        continue;\n"
        "    }\n"
        "    found = 1;\n"
        "    alias = driver[i].alias;\n"
        "    if (alias == \"\") {\n"
        "        alias = \"<none>\";\n"
        "    }\n"
        "    product = driver[i].product;\n"
        "    if (product == \"\") {\n"
        "        product = \"<none>\";\n"
        "    }\n"
        "    print(\"Alias              : \" + alias);\n"
        "    print(\"Type               : \" + driver[i].type_name + \" (\" + driver[i].type + \")\");\n"
        "    print(\"Version fields     : \" + driver[i].version_major + \".\" + driver[i].version_minor);\n"
        "    print(\"Designer           : \" + driver[i].designer);\n"
        "    print(\"Manufacturer       : \" + driver[i].manufacturer);\n"
        "    print(\"Product            : \" + product);\n"
        "    print(\"Flags              : \" + driver[i].flags);\n"
        "    if (driver[i].ready != 0) {\n"
        "        print(\"Ready              : yes\");\n"
        "    } else {\n"
        "        print(\"Ready              : no\");\n"
        "    }\n"
        "    print(\"Enum domains       : \" + driver[i].enum_domain_count);\n"
        "    if (driver[i].enum_domain_count == 0) {\n"
        "        print(\"  <none>\");\n"
        "    } else {\n"
        "        for (j = 0; j < driver[i].enum_domain_count; j = j + 1) {\n"
        "            print(\"  \" + j + \": \" + driver[i].enum_domain[j]);\n"
        "        }\n"
        "    }\n"
        "    mode_count = driver[i].mode.count;\n"
        "    print(\"Mode count         : \" + mode_count);\n"
        "    if (driver[i].type != 11) {\n"
        "        print(\"Mode details       : not applicable to non-graphics drivers\");\n"
        "    } else if (mode_count == 0) {\n"
        "        print(\"Mode details       : this graphics driver does not expose any selectable mode\");\n"
        "    } else {\n"
        "        modes = driver[i].mode;\n"
        "        for (m = 0; m < mode_count; m = m + 1) {\n"
        "            mode_width = modes[m].width;\n"
        "            mode_height = modes[m].height;\n"
        "            mode_bpp = modes[m].bpp;\n"
        "            print(\"  \" + m + \": \" + mode_width + \"x\" + mode_height + \"x\" + mode_bpp);\n"
        "        }\n"
        "    }\n"
        "}\n"
        "if (found == 0) {\n"
        "    print(\"driver: alias '\" + target_alias + \"' not found\");\n"
        "    print(\"known aliases:\");\n"
        "    known = 0;\n"
        "    for (i = 0; i < count; i = i + 1) {\n"
        "        alias = driver[i].alias;\n"
        "        if (alias == \"\") {\n"
        "            continue;\n"
        "        }\n"
        "        print(alias);\n"
        "        known = known + 1;\n"
        "    }\n"
        "    if (known == 0) {\n"
        "        print(\"none\");\n"
        "    }\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_TASK_LIST] = (LPCSTR)
        "count = task.count;\n"
        "if (count == 0) {\n"
        "    print(\"No task detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(i + \" handle=\" + task[i].handle + \" name=\" + task[i].name + \" type=\" + task[i].type + \" status=\" + task[i].status + \" priority=\" + task[i].priority + \" flags=\" + task[i].flags + \" exit=\" + task[i].exit_code);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_DISK_LIST] = (LPCSTR)
        "count = storage.count;\n"
        "if (count == 0) {\n"
        "    print(\"No disk detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"disk=\" + i + \" type=\" + storage[i].type + \" removable=\" + storage[i].removable + \" access=\" + storage[i].access + \" bytes_per_sector=\" + storage[i].bytes_per_sector + \" sectors_high=\" + storage[i].num_sectors_high + \" sectors_low=\" + storage[i].num_sectors_low + \" manufacturer=\" + storage[i].driver_manufacturer + \" product=\" + storage[i].driver_product);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_FILE_SYSTEM_LIST] = (LPCSTR)
        "active_partition_name = file_system.active_partition_name;\n"
        "count = file_system.mounted.count;\n"
        "if (count == 0 && file_system.unused.count == 0) {\n"
        "    print(\"No file system detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    active = 0;\n"
        "    if (active_partition_name != \"\" && file_system.mounted[i].name == active_partition_name) {\n"
        "        active = 1;\n"
        "    }\n"
        "    print(\"state=mounted name=\" + file_system.mounted[i].name + \" scheme=\" + file_system.mounted[i].scheme_name + \" type=\" + file_system.mounted[i].type_name + \" format=\" + file_system.mounted[i].format_name + \" partition_index=\" + file_system.mounted[i].index + \" start_sector=\" + file_system.mounted[i].start_sector + \" num_sectors=\" + file_system.mounted[i].num_sectors + \" active=\" + active + \" removable=\" + file_system.mounted[i].removable + \" read_only=\" + file_system.mounted[i].read_only + \" fs_driver_manufacturer=\" + file_system.mounted[i].driver_manufacturer + \" fs_driver_product=\" + file_system.mounted[i].driver_product + \" storage_manufacturer=\" + file_system.mounted[i].storage_manufacturer + \" storage_product=\" + file_system.mounted[i].storage_product);\n"
        "}\n"
        "count = file_system.unused.count;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    active = 0;\n"
        "    if (active_partition_name != \"\" && file_system.unused[i].name == active_partition_name) {\n"
        "        active = 1;\n"
        "    }\n"
        "    print(\"state=unused name=\" + file_system.unused[i].name + \" scheme=\" + file_system.unused[i].scheme_name + \" type=\" + file_system.unused[i].type_name + \" format=\" + file_system.unused[i].format_name + \" partition_index=\" + file_system.unused[i].index + \" start_sector=\" + file_system.unused[i].start_sector + \" num_sectors=\" + file_system.unused[i].num_sectors + \" active=\" + active + \" removable=\" + file_system.unused[i].removable + \" read_only=\" + file_system.unused[i].read_only + \" fs_driver_manufacturer=\" + file_system.unused[i].driver_manufacturer + \" fs_driver_product=\" + file_system.unused[i].driver_product + \" storage_manufacturer=\" + file_system.unused[i].storage_manufacturer + \" storage_product=\" + file_system.unused[i].storage_product);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_FILE_SYSTEM_LIST_LONG] = (LPCSTR)
        "active = file_system.active_partition_name;\n"
        "print(\"General information\");\n"
        "if (active == \"\") {\n"
        "    print(\"Active partition : <none>\");\n"
        "} else {\n"
        "    print(\"Active partition : \" + active);\n"
        "}\n"
        "print(\"\");\n"
        "print(\"Discovered file systems\");\n"
        "count = file_system.mounted.count;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"Name         : \" + file_system.mounted[i].name);\n"
        "    if (file_system.mounted[i].mounted != 0) {\n"
        "        print(\"Mounted      : YES\");\n"
        "    } else {\n"
        "        print(\"Mounted      : NO\");\n"
        "    }\n"
        "    if (file_system.mounted[i].driver_product == \"\") {\n"
        "        print(\"FS driver    : <none>\");\n"
        "    } else {\n"
        "        print(\"FS driver    : \" + file_system.mounted[i].driver_manufacturer + \" / \" + file_system.mounted[i].driver_product);\n"
        "    }\n"
        "    print(\"Scheme       : \" + file_system.mounted[i].scheme_name);\n"
        "    print(\"Type         : \" + file_system.mounted[i].type_name);\n"
        "    print(\"Format       : \" + file_system.mounted[i].format_name);\n"
        "    print(\"Index        : \" + file_system.mounted[i].index);\n"
        "    print(\"Start sector : \" + file_system.mounted[i].start_sector);\n"
        "    print(\"Size         : \" + file_system.mounted[i].num_sectors + \" sectors\");\n"
        "    if ((file_system.mounted[i].flags & 1) != 0) {\n"
        "        print(\"Active       : YES\");\n"
        "    } else {\n"
        "        print(\"Active       : NO\");\n"
        "    }\n"
        "    if (file_system.mounted[i].scheme == 1) {\n"
        "        print(\"Type id      : \" + file_system.mounted[i].type);\n"
        "    }\n"
        "    if (file_system.mounted[i].has_storage != 0) {\n"
        "        print(\"Storage      : \" + file_system.mounted[i].storage_manufacturer + \" / \" + file_system.mounted[i].storage_product);\n"
        "        if (file_system.mounted[i].removable != 0) {\n"
        "            print(\"Removable    : YES\");\n"
        "        } else {\n"
        "            print(\"Removable    : NO\");\n"
        "        }\n"
        "        if (file_system.mounted[i].read_only != 0) {\n"
        "            print(\"Read only    : YES\");\n"
        "        } else {\n"
        "            print(\"Read only    : NO\");\n"
        "        }\n"
        "        print(\"Disk sectors : \" + file_system.mounted[i].disk_num_sectors_high + \", \" + file_system.mounted[i].disk_num_sectors_low);\n"
        "    } else {\n"
        "        print(\"Storage      : <none>\");\n"
        "    }\n"
        "    print(\"\");\n"
        "}\n"
        "count = file_system.unused.count;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"Name         : \" + file_system.unused[i].name);\n"
        "    if (file_system.unused[i].mounted != 0) {\n"
        "        print(\"Mounted      : YES\");\n"
        "    } else {\n"
        "        print(\"Mounted      : NO\");\n"
        "    }\n"
        "    if (file_system.unused[i].driver_product == \"\") {\n"
        "        print(\"FS driver    : <none>\");\n"
        "    } else {\n"
        "        print(\"FS driver    : \" + file_system.unused[i].driver_manufacturer + \" / \" + file_system.unused[i].driver_product);\n"
        "    }\n"
        "    print(\"Scheme       : \" + file_system.unused[i].scheme_name);\n"
        "    print(\"Type         : \" + file_system.unused[i].type_name);\n"
        "    print(\"Format       : \" + file_system.unused[i].format_name);\n"
        "    print(\"Index        : \" + file_system.unused[i].index);\n"
        "    print(\"Start sector : \" + file_system.unused[i].start_sector);\n"
        "    print(\"Size         : \" + file_system.unused[i].num_sectors + \" sectors\");\n"
        "    if ((file_system.unused[i].flags & 1) != 0) {\n"
        "        print(\"Active       : YES\");\n"
        "    } else {\n"
        "        print(\"Active       : NO\");\n"
        "    }\n"
        "    if (file_system.unused[i].scheme == 1) {\n"
        "        print(\"Type id      : \" + file_system.unused[i].type);\n"
        "    }\n"
        "    if (file_system.unused[i].has_storage != 0) {\n"
        "        print(\"Storage      : \" + file_system.unused[i].storage_manufacturer + \" / \" + file_system.unused[i].storage_product);\n"
        "        if (file_system.unused[i].removable != 0) {\n"
        "            print(\"Removable    : YES\");\n"
        "        } else {\n"
        "            print(\"Removable    : NO\");\n"
        "        }\n"
        "        if (file_system.unused[i].read_only != 0) {\n"
        "            print(\"Read only    : YES\");\n"
        "        } else {\n"
        "            print(\"Read only    : NO\");\n"
        "        }\n"
        "        print(\"Disk sectors : \" + file_system.unused[i].disk_num_sectors_high + \", \" + file_system.unused[i].disk_num_sectors_low);\n"
        "    } else {\n"
        "        print(\"Storage      : <none>\");\n"
        "    }\n"
        "    print(\"\");\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_MEMORY_MAP] = (LPCSTR)
        "count = memory_map.kernel_region.count;\n"
        "print(\"Kernel regions: \" + count);\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    line = \"\" + i + \": tag=\" + memory_map.kernel_region[i].tag + \" base=(\" + memory_map.kernel_region[i].base_high + \",\" + memory_map.kernel_region[i].base_low + \") size=\" + memory_map.kernel_region[i].size;\n"
        "    if (memory_map.kernel_region[i].physical_known != 0) {\n"
        "        line = line + \" phys=(\" + memory_map.kernel_region[i].physical_high + \",\" + memory_map.kernel_region[i].physical_low + \")\";\n"
        "    } else {\n"
        "        line = line + \" phys=?\";\n"
        "    }\n"
        "    print(line);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_NETWORK_DEVICES] = (LPCSTR)
        "count = network.device.count;\n"
        "if (count == 0) {\n"
        "    print(\"No network device detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"Name         : \" + network.device[i].name);\n"
        "    print(\"Manufacturer : \" + network.device[i].manufacturer);\n"
        "    print(\"Product      : \" + network.device[i].product);\n"
        "    print(\"MAC          : \" + network.device[i].mac_0 + \":\" + network.device[i].mac_1 + \":\" + network.device[i].mac_2 + \":\" + network.device[i].mac_3 + \":\" + network.device[i].mac_4 + \":\" + network.device[i].mac_5);\n"
        "    print(\"IP Address   : \" + network.device[i].ip_0 + \".\" + network.device[i].ip_1 + \".\" + network.device[i].ip_2 + \".\" + network.device[i].ip_3);\n"
        "    if (network.device[i].link_up != 0) {\n"
        "        print(\"Link         : UP\");\n"
        "    } else {\n"
        "        print(\"Link         : DOWN\");\n"
        "    }\n"
        "    print(\"Speed        : \" + network.device[i].speed_mbps + \" Mbps\");\n"
        "    if (network.device[i].duplex_full != 0) {\n"
        "        print(\"Duplex       : FULL\");\n"
        "    } else {\n"
        "        print(\"Duplex       : HALF\");\n"
        "    }\n"
        "    print(\"MTU          : \" + network.device[i].mtu);\n"
        "    if (network.device[i].initialized != 0) {\n"
        "        print(\"Initialized  : YES\");\n"
        "    } else {\n"
        "        print(\"Initialized  : NO\");\n"
        "    }\n"
        "    print(\"\");\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_PORTS] = (LPCSTR)
        "count = usb.port.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB port detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"port=\" + usb.port[i].port_number + \" bus=\" + usb.port[i].bus + \" device=\" + usb.port[i].device + \" function=\" + usb.port[i].function + \" speed_id=\" + usb.port[i].speed_id + \" connected=\" + usb.port[i].connected + \" enabled=\" + usb.port[i].enabled + \" status=\" + usb.port[i].port_status);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_DEVICES] = (LPCSTR)
        "count = usb.device.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB device detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"addr=\" + usb.device[i].address + \" bus=\" + usb.device[i].bus + \" device=\" + usb.device[i].device + \" function=\" + usb.device[i].function + \" port=\" + usb.device[i].port_number + \" speed_id=\" + usb.device[i].speed_id + \" vid=\" + usb.device[i].vendor_id + \" pid=\" + usb.device[i].product_id);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_DRIVES] = (LPCSTR)
        "count = usb.drive.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB drive detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    state = \"offline\";\n"
        "    if (usb.drive[i].present != 0) {\n"
        "        state = \"online\";\n"
        "    }\n"
        "    print(\"usb\" + i + \": addr=\" + usb.drive[i].address + \" vid=\" + usb.drive[i].vendor_id + \" pid=\" + usb.drive[i].product_id + \" blocks=\" + usb.drive[i].block_count + \" block_size=\" + usb.drive[i].block_size + \" state=\" + state);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_DEVICE_TREE] = (LPCSTR)
        "count = usb.node.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB device tree detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (usb.node[i].node_type == 1) {\n"
        "        print(\"Device Port \" + usb.node[i].port_number + \" Addr \" + usb.node[i].address + \" VID=\" + usb.node[i].vendor_id + \" PID=\" + usb.node[i].product_id + \" Class=\" + usb.node[i].device_class + \"/\" + usb.node[i].device_sub_class + \"/\" + usb.node[i].device_protocol + \" Speed=\" + usb.node[i].speed_id);\n"
        "    } else if (usb.node[i].node_type == 2) {\n"
        "        print(\"  Config \" + usb.node[i].config_value + \" Attr=\" + usb.node[i].config_attributes + \" MaxPower=\" + usb.node[i].config_max_power);\n"
        "    } else if (usb.node[i].node_type == 3) {\n"
        "        print(\"    Interface \" + usb.node[i].interface_number + \" Alt=\" + usb.node[i].alternate_setting + \" Class=\" + usb.node[i].interface_class + \"/\" + usb.node[i].interface_sub_class + \"/\" + usb.node[i].interface_protocol);\n"
        "    } else if (usb.node[i].node_type == 4) {\n"
        "        direction = \"OUT\";\n"
        "        if ((usb.node[i].endpoint_address & 128) != 0) {\n"
        "            direction = \"IN\";\n"
        "        }\n"
        "        print(\"      Endpoint \" + usb.node[i].endpoint_address + \" \" + direction + \" Attr=\" + usb.node[i].endpoint_attributes + \" MaxPacket=\" + usb.node[i].endpoint_max_packet_size + \" Interval=\" + usb.node[i].endpoint_interval);\n"
        "    }\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_PROBE] = (LPCSTR)
        "count = usb.port.count;\n"
        "if (count == 0) {\n"
        "    print(\"No xHCI controller detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (usb.port[i].connected != 0) {\n"
        "        line = \"port=\" + usb.port[i].port_number + \" error=\" + usb.port[i].last_enum_error_text;\n"
        "        if (usb.port[i].last_enum_error == 5) {\n"
        "            line = line + \" C=\" + usb.port[i].last_enum_completion;\n"
        "        }\n"
        "        print(line);\n"
        "    }\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_NVME_LIST] = (LPCSTR)
        "count = pci_device.count;\n"
        "found = 0;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (pci_device[i].base_class != 1 || pci_device[i].sub_class != 8 || pci_device[i].prog_if != 2) {\n"
        "        continue;\n"
        "    }\n"
        "    print(\"nvme\" + found + \": bus=\" + pci_device[i].bus + \" device=\" + pci_device[i].device + \" function=\" + pci_device[i].function + \" vendor_id=\" + pci_device[i].vendor_id + \" device_id=\" + pci_device[i].device_id + \" revision=\" + pci_device[i].revision);\n"
        "    found = found + 1;\n"
        "}\n"
        "if (found == 0) {\n"
        "    print(\"No NVMe device detected\");\n"
        "}\n"
};

/************************************************************************/

/**
 * @brief Get one embedded E0 source by identifier.
 * @param ScriptId Embedded script identifier.
 * @return Embedded script text.
 */
LPCSTR ShellGetEmbeddedScript(SHELL_EMBEDDED_SCRIPT_ID ScriptId) {
    if ((UINT)ScriptId >= SHELL_EMBEDDED_SCRIPT_COUNT) {
        return NULL;
    }

    return G_EmbeddedScripts[ScriptId];
}
