/************************************************************************\

    EXOS Kernel
    Copyright (c) 1999-2025 Jango73

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.


    Shell - Embedded E0 Scripts

\************************************************************************/

#include "shell/Shell-Embedded-Scripts.h"

/************************************************************************/

static LPCSTR G_EmbeddedScripts[SHELL_EMBEDDED_SCRIPT_COUNT] = {
    [SHELL_EMBEDDED_SCRIPT_DRIVER_LIST] = (LPCSTR)
        "count = driver.count;\n"
        "if (count == 0) {\n"
        "    print(\"No driver detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    alias = driver[i].alias;\n"
        "    if (alias == \"\") {\n"
        "        alias = \"<none>\";\n"
        "    }\n"
        "    product = driver[i].product;\n"
        "    if (product == \"\") {\n"
        "        product = \"<none>\";\n"
        "    }\n"
        "    print(alias + \" type=\" + driver[i].typeName + \" ready=\" + driver[i].ready + \" product=\" + product);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_DRIVER_DETAILS] = (LPCSTR)
        "count = driver.count;\n"
        "found = 0;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (driver[i].alias != target_alias) {\n"
        "        continue;\n"
        "    }\n"
        "    found = 1;\n"
        "    alias = driver[i].alias;\n"
        "    if (alias == \"\") {\n"
        "        alias = \"<none>\";\n"
        "    }\n"
        "    product = driver[i].product;\n"
        "    if (product == \"\") {\n"
        "        product = \"<none>\";\n"
        "    }\n"
        "    print(\"Alias              : \" + alias);\n"
        "    print(\"Type               : \" + driver[i].typeName + \" (\" + driver[i].type + \")\");\n"
        "    print(\"Version fields     : \" + driver[i].versionMajor + \".\" + driver[i].versionMinor);\n"
        "    print(\"Designer           : \" + driver[i].designer);\n"
        "    print(\"Manufacturer       : \" + driver[i].manufacturer);\n"
        "    print(\"Product            : \" + product);\n"
        "    print(\"Flags              : \" + driver[i].flags);\n"
        "    if (driver[i].ready != 0) {\n"
        "        print(\"Ready              : yes\");\n"
        "    } else {\n"
        "        print(\"Ready              : no\");\n"
        "    }\n"
        "    print(\"Enum domains       : \" + driver[i].enumDomainCount);\n"
        "    if (driver[i].enumDomainCount == 0) {\n"
        "        print(\"  <none>\");\n"
        "    } else {\n"
        "        for (j = 0; j < driver[i].enumDomainCount; j = j + 1) {\n"
        "            print(\"  \" + j + \": \" + driver[i].enumDomain[j]);\n"
        "        }\n"
        "    }\n"
        "    mode_count = driver[i].mode.count;\n"
        "    print(\"Mode count         : \" + mode_count);\n"
        "    if (driver[i].type != 11) {\n"
        "        print(\"Mode details       : not applicable to non-graphics drivers\");\n"
        "    } else if (mode_count == 0) {\n"
        "        print(\"Mode details       : this graphics driver does not expose any selectable mode\");\n"
        "    } else {\n"
        "        modes = driver[i].mode;\n"
        "        for (m = 0; m < mode_count; m = m + 1) {\n"
        "            mode_width = modes[m].width;\n"
        "            mode_height = modes[m].height;\n"
        "            mode_bpp = modes[m].bpp;\n"
        "            print(\"  \" + m + \": \" + mode_width + \"x\" + mode_height + \"x\" + mode_bpp);\n"
        "        }\n"
        "    }\n"
        "}\n"
        "if (found == 0) {\n"
        "    print(\"driver: alias '\" + target_alias + \"' not found\");\n"
        "    print(\"known aliases:\");\n"
        "    known = 0;\n"
        "    for (i = 0; i < count; i = i + 1) {\n"
        "        alias = driver[i].alias;\n"
        "        if (alias == \"\") {\n"
        "            continue;\n"
        "        }\n"
        "        print(alias);\n"
        "        known = known + 1;\n"
        "    }\n"
        "    if (known == 0) {\n"
        "        print(\"none\");\n"
        "    }\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_TASK_LIST] = (LPCSTR)
        "count = task.count;\n"
        "if (count == 0) {\n"
        "    print(\"No task detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(i + \" handle=\" + task[i].handle + \" name=\" + task[i].name + \" type=\" + task[i].type + \" status=\" + task[i].status + \" priority=\" + task[i].priority + \" flags=\" + task[i].flags + \" exit=\" + task[i].exitCode);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_DISK_LIST] = (LPCSTR)
        "count = storage.count;\n"
        "if (count == 0) {\n"
        "    print(\"No disk detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"disk=\" + i + \" type=\" + storage[i].type + \" removable=\" + storage[i].removable + \" access=\" + storage[i].access + \" bytesPerSector=\" + storage[i].bytesPerSector + \" sectors_high=\" + storage[i].numSectorsHigh + \" sectors_low=\" + storage[i].numSectorsLow + \" manufacturer=\" + storage[i].driverManufacturer + \" product=\" + storage[i].driverProduct);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_FILE_SYSTEM_LIST] = (LPCSTR)
        "activePartitionName = fileSystem.activePartitionName;\n"
        "count = fileSystem.mounted.count;\n"
        "if (count == 0 && fileSystem.unused.count == 0) {\n"
        "    print(\"No file system detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    active = 0;\n"
        "    if (activePartitionName != \"\" && fileSystem.mounted[i].name == activePartitionName) {\n"
        "        active = 1;\n"
        "    }\n"
        "    print(\"state=mounted name=\" + fileSystem.mounted[i].name + \" scheme=\" + fileSystem.mounted[i].schemeName + \" type=\" + fileSystem.mounted[i].typeName + \" format=\" + fileSystem.mounted[i].formatName + \" partition_index=\" + fileSystem.mounted[i].index + \" startSector=\" + fileSystem.mounted[i].startSector + \" numSectors=\" + fileSystem.mounted[i].numSectors + \" active=\" + active + \" removable=\" + fileSystem.mounted[i].removable + \" readOnly=\" + fileSystem.mounted[i].readOnly + \" fs_driver_manufacturer=\" + fileSystem.mounted[i].driverManufacturer + \" fs_driver_product=\" + fileSystem.mounted[i].driverProduct + \" storageManufacturer=\" + fileSystem.mounted[i].storageManufacturer + \" storageProduct=\" + fileSystem.mounted[i].storageProduct);\n"
        "}\n"
        "count = fileSystem.unused.count;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    active = 0;\n"
        "    if (activePartitionName != \"\" && fileSystem.unused[i].name == activePartitionName) {\n"
        "        active = 1;\n"
        "    }\n"
        "    print(\"state=unused name=\" + fileSystem.unused[i].name + \" scheme=\" + fileSystem.unused[i].schemeName + \" type=\" + fileSystem.unused[i].typeName + \" format=\" + fileSystem.unused[i].formatName + \" partition_index=\" + fileSystem.unused[i].index + \" startSector=\" + fileSystem.unused[i].startSector + \" numSectors=\" + fileSystem.unused[i].numSectors + \" active=\" + active + \" removable=\" + fileSystem.unused[i].removable + \" readOnly=\" + fileSystem.unused[i].readOnly + \" fs_driver_manufacturer=\" + fileSystem.unused[i].driverManufacturer + \" fs_driver_product=\" + fileSystem.unused[i].driverProduct + \" storageManufacturer=\" + fileSystem.unused[i].storageManufacturer + \" storageProduct=\" + fileSystem.unused[i].storageProduct);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_FILE_SYSTEM_LIST_LONG] = (LPCSTR)
        "active = fileSystem.activePartitionName;\n"
        "print(\"General information\");\n"
        "if (active == \"\") {\n"
        "    print(\"Active partition : <none>\");\n"
        "} else {\n"
        "    print(\"Active partition : \" + active);\n"
        "}\n"
        "print(\"\");\n"
        "print(\"Discovered file systems\");\n"
        "count = fileSystem.mounted.count;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"Name         : \" + fileSystem.mounted[i].name);\n"
        "    if (fileSystem.mounted[i].mounted != 0) {\n"
        "        print(\"Mounted      : YES\");\n"
        "    } else {\n"
        "        print(\"Mounted      : NO\");\n"
        "    }\n"
        "    if (fileSystem.mounted[i].driverProduct == \"\") {\n"
        "        print(\"FS driver    : <none>\");\n"
        "    } else {\n"
        "        print(\"FS driver    : \" + fileSystem.mounted[i].driverManufacturer + \" / \" + fileSystem.mounted[i].driverProduct);\n"
        "    }\n"
        "    print(\"Scheme       : \" + fileSystem.mounted[i].schemeName);\n"
        "    print(\"Type         : \" + fileSystem.mounted[i].typeName);\n"
        "    print(\"Format       : \" + fileSystem.mounted[i].formatName);\n"
        "    print(\"Index        : \" + fileSystem.mounted[i].index);\n"
        "    print(\"Start sector : \" + fileSystem.mounted[i].startSector);\n"
        "    print(\"Size         : \" + fileSystem.mounted[i].numSectors + \" sectors\");\n"
        "    if ((fileSystem.mounted[i].flags & 1) != 0) {\n"
        "        print(\"Active       : YES\");\n"
        "    } else {\n"
        "        print(\"Active       : NO\");\n"
        "    }\n"
        "    if (fileSystem.mounted[i].scheme == 1) {\n"
        "        print(\"Type id      : \" + fileSystem.mounted[i].type);\n"
        "    }\n"
        "    if (fileSystem.mounted[i].hasStorage != 0) {\n"
        "        print(\"Storage      : \" + fileSystem.mounted[i].storageManufacturer + \" / \" + fileSystem.mounted[i].storageProduct);\n"
        "        if (fileSystem.mounted[i].removable != 0) {\n"
        "            print(\"Removable    : YES\");\n"
        "        } else {\n"
        "            print(\"Removable    : NO\");\n"
        "        }\n"
        "        if (fileSystem.mounted[i].readOnly != 0) {\n"
        "            print(\"Read only    : YES\");\n"
        "        } else {\n"
        "            print(\"Read only    : NO\");\n"
        "        }\n"
        "        print(\"Disk sectors : \" + fileSystem.mounted[i].diskNumSectorsHigh + \", \" + fileSystem.mounted[i].diskNumSectorsLow);\n"
        "    } else {\n"
        "        print(\"Storage      : <none>\");\n"
        "    }\n"
        "    print(\"\");\n"
        "}\n"
        "count = fileSystem.unused.count;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"Name         : \" + fileSystem.unused[i].name);\n"
        "    if (fileSystem.unused[i].mounted != 0) {\n"
        "        print(\"Mounted      : YES\");\n"
        "    } else {\n"
        "        print(\"Mounted      : NO\");\n"
        "    }\n"
        "    if (fileSystem.unused[i].driverProduct == \"\") {\n"
        "        print(\"FS driver    : <none>\");\n"
        "    } else {\n"
        "        print(\"FS driver    : \" + fileSystem.unused[i].driverManufacturer + \" / \" + fileSystem.unused[i].driverProduct);\n"
        "    }\n"
        "    print(\"Scheme       : \" + fileSystem.unused[i].schemeName);\n"
        "    print(\"Type         : \" + fileSystem.unused[i].typeName);\n"
        "    print(\"Format       : \" + fileSystem.unused[i].formatName);\n"
        "    print(\"Index        : \" + fileSystem.unused[i].index);\n"
        "    print(\"Start sector : \" + fileSystem.unused[i].startSector);\n"
        "    print(\"Size         : \" + fileSystem.unused[i].numSectors + \" sectors\");\n"
        "    if ((fileSystem.unused[i].flags & 1) != 0) {\n"
        "        print(\"Active       : YES\");\n"
        "    } else {\n"
        "        print(\"Active       : NO\");\n"
        "    }\n"
        "    if (fileSystem.unused[i].scheme == 1) {\n"
        "        print(\"Type id      : \" + fileSystem.unused[i].type);\n"
        "    }\n"
        "    if (fileSystem.unused[i].hasStorage != 0) {\n"
        "        print(\"Storage      : \" + fileSystem.unused[i].storageManufacturer + \" / \" + fileSystem.unused[i].storageProduct);\n"
        "        if (fileSystem.unused[i].removable != 0) {\n"
        "            print(\"Removable    : YES\");\n"
        "        } else {\n"
        "            print(\"Removable    : NO\");\n"
        "        }\n"
        "        if (fileSystem.unused[i].readOnly != 0) {\n"
        "            print(\"Read only    : YES\");\n"
        "        } else {\n"
        "            print(\"Read only    : NO\");\n"
        "        }\n"
        "        print(\"Disk sectors : \" + fileSystem.unused[i].diskNumSectorsHigh + \", \" + fileSystem.unused[i].diskNumSectorsLow);\n"
        "    } else {\n"
        "        print(\"Storage      : <none>\");\n"
        "    }\n"
        "    print(\"\");\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_MEMORY_MAP] = (LPCSTR)
        "count = memoryMap.kernelRegion.count;\n"
        "print(\"Kernel regions: \" + count);\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    line = \"\" + i + \": tag=\" + memoryMap.kernelRegion[i].tag + \" base=(\" + memoryMap.kernelRegion[i].baseHigh + \",\" + memoryMap.kernelRegion[i].baseLow + \") size=\" + memoryMap.kernelRegion[i].size;\n"
        "    if (memoryMap.kernelRegion[i].physicalKnown != 0) {\n"
        "        line = line + \" phys=(\" + memoryMap.kernelRegion[i].physicalHigh + \",\" + memoryMap.kernelRegion[i].physicalLow + \")\";\n"
        "    } else {\n"
        "        line = line + \" phys=?\";\n"
        "    }\n"
        "    print(line);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_NETWORK_DEVICES] = (LPCSTR)
        "count = network.device.count;\n"
        "if (count == 0) {\n"
        "    print(\"No network device detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"Name         : \" + network.device[i].name);\n"
        "    print(\"Manufacturer : \" + network.device[i].manufacturer);\n"
        "    print(\"Product      : \" + network.device[i].product);\n"
        "    print(\"MAC          : \" + network.device[i].mac0 + \":\" + network.device[i].mac1 + \":\" + network.device[i].mac2 + \":\" + network.device[i].mac3 + \":\" + network.device[i].mac4 + \":\" + network.device[i].mac5);\n"
        "    print(\"IP Address   : \" + network.device[i].ip0 + \".\" + network.device[i].ip1 + \".\" + network.device[i].ip2 + \".\" + network.device[i].ip3);\n"
        "    if (network.device[i].linkUp != 0) {\n"
        "        print(\"Link         : UP\");\n"
        "    } else {\n"
        "        print(\"Link         : DOWN\");\n"
        "    }\n"
        "    print(\"Speed        : \" + network.device[i].speedMbps + \" Mbps\");\n"
        "    if (network.device[i].duplexFull != 0) {\n"
        "        print(\"Duplex       : FULL\");\n"
        "    } else {\n"
        "        print(\"Duplex       : HALF\");\n"
        "    }\n"
        "    print(\"MTU          : \" + network.device[i].mtu);\n"
        "    if (network.device[i].initialized != 0) {\n"
        "        print(\"Initialized  : YES\");\n"
        "    } else {\n"
        "        print(\"Initialized  : NO\");\n"
        "    }\n"
        "    print(\"\");\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_PORTS] = (LPCSTR)
        "count = usb.port.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB port detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"port=\" + usb.port[i].portNumber + \" bus=\" + usb.port[i].bus + \" device=\" + usb.port[i].device + \" function=\" + usb.port[i].function + \" speedId=\" + usb.port[i].speedId + \" connected=\" + usb.port[i].connected + \" enabled=\" + usb.port[i].enabled + \" status=\" + usb.port[i].portStatus);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_DEVICES] = (LPCSTR)
        "count = usb.device.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB device detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    print(\"addr=\" + usb.device[i].address + \" bus=\" + usb.device[i].bus + \" device=\" + usb.device[i].device + \" function=\" + usb.device[i].function + \" port=\" + usb.device[i].portNumber + \" speedId=\" + usb.device[i].speedId + \" vid=\" + usb.device[i].vendorId + \" pid=\" + usb.device[i].productId);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_DRIVES] = (LPCSTR)
        "count = usb.drive.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB drive detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    state = \"offline\";\n"
        "    if (usb.drive[i].present != 0) {\n"
        "        state = \"online\";\n"
        "    }\n"
        "    print(\"usb\" + i + \": addr=\" + usb.drive[i].address + \" vid=\" + usb.drive[i].vendorId + \" pid=\" + usb.drive[i].productId + \" blocks=\" + usb.drive[i].blockCount + \" blockSize=\" + usb.drive[i].blockSize + \" state=\" + state);\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_DEVICE_TREE] = (LPCSTR)
        "count = usb.node.count;\n"
        "if (count == 0) {\n"
        "    print(\"No USB device tree detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (usb.node[i].nodeType == 1) {\n"
        "        print(\"Device Port \" + usb.node[i].portNumber + \" Addr \" + usb.node[i].address + \" VID=\" + usb.node[i].vendorId + \" PID=\" + usb.node[i].productId + \" Class=\" + usb.node[i].deviceClass + \"/\" + usb.node[i].deviceSubClass + \"/\" + usb.node[i].deviceProtocol + \" Speed=\" + usb.node[i].speedId);\n"
        "    } else if (usb.node[i].nodeType == 2) {\n"
        "        print(\"  Config \" + usb.node[i].configValue + \" Attr=\" + usb.node[i].configAttributes + \" MaxPower=\" + usb.node[i].configMaxPower);\n"
        "    } else if (usb.node[i].nodeType == 3) {\n"
        "        print(\"    Interface \" + usb.node[i].interfaceNumber + \" Alt=\" + usb.node[i].alternateSetting + \" Class=\" + usb.node[i].interfaceClass + \"/\" + usb.node[i].interfaceSubClass + \"/\" + usb.node[i].interfaceProtocol);\n"
        "    } else if (usb.node[i].nodeType == 4) {\n"
        "        direction = \"OUT\";\n"
        "        if ((usb.node[i].endpointAddress & 128) != 0) {\n"
        "            direction = \"IN\";\n"
        "        }\n"
        "        print(\"      Endpoint \" + usb.node[i].endpointAddress + \" \" + direction + \" Attr=\" + usb.node[i].endpointAttributes + \" MaxPacket=\" + usb.node[i].endpointMaxPacketSize + \" Interval=\" + usb.node[i].endpointInterval);\n"
        "    }\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_USB_PROBE] = (LPCSTR)
        "count = usb.port.count;\n"
        "if (count == 0) {\n"
        "    print(\"No xHCI controller detected\");\n"
        "}\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (usb.port[i].connected != 0) {\n"
        "        line = \"port=\" + usb.port[i].portNumber + \" error=\" + usb.port[i].lastEnumErrorText;\n"
        "        if (usb.port[i].lastEnumError == 5) {\n"
        "            line = line + \" C=\" + usb.port[i].lastEnumCompletion;\n"
        "        }\n"
        "        print(line);\n"
        "    }\n"
        "}\n",
    [SHELL_EMBEDDED_SCRIPT_NVME_LIST] = (LPCSTR)
        "count = pciDevice.count;\n"
        "found = 0;\n"
        "for (i = 0; i < count; i = i + 1) {\n"
        "    if (pciDevice[i].baseClass != 1 || pciDevice[i].subClass != 8 || pciDevice[i].progIf != 2) {\n"
        "        continue;\n"
        "    }\n"
        "    print(\"nvme\" + found + \": bus=\" + pciDevice[i].bus + \" device=\" + pciDevice[i].device + \" function=\" + pciDevice[i].function + \" vendorId=\" + pciDevice[i].vendorId + \" deviceId=\" + pciDevice[i].deviceId + \" revision=\" + pciDevice[i].revision);\n"
        "    found = found + 1;\n"
        "}\n"
        "if (found == 0) {\n"
        "    print(\"No NVMe device detected\");\n"
        "}\n"
};

/************************************************************************/

/**
 * @brief Get one embedded E0 source by identifier.
 * @param ScriptId Embedded script identifier.
 * @return Embedded script text.
 */
LPCSTR ShellGetEmbeddedScript(SHELL_EMBEDDED_SCRIPT_ID ScriptId) {
    if ((UINT)ScriptId >= SHELL_EMBEDDED_SCRIPT_COUNT) {
        return NULL;
    }

    return G_EmbeddedScripts[ScriptId];
}
