################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2026 Jango73
#
################################################################################

APP_NAME := module-import
APP_TYPE := module
APP_SOURCES := source/module-import.c

include ../../../runtime/make/exos.mk
