################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := tictactoe
APP_SOURCES := source/tictactoe.c

include ../../runtime/make/exos.mk
