
; Int.inc

;----------------------------------------------------------

extern Interrupt_Default           : near
extern Interrupt_DivideError       : near
extern Interrupt_BreakPoint        : near
extern Interrupt_Overflow          : near
extern Interrupt_BoundRange        : near
extern Interrupt_StackFault        : near
extern Interrupt_GeneralProtection : near
extern Interrupt_PageFault         : near
extern Interrupt_Clock             : near
extern Interrupt_Keyboard          : near

;----------------------------------------------------------
