################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := hello
APP_SOURCES := source/hello.c

include ../../../runtime/make/exos.mk
