[[SystemFS.Mount]]
FileSystem="hd0p0"
Path="/os"

[[SystemFS.Mount]]
FileSystem="hd1p0"
Path="/work"

[Keyboard]
# Available : de-DE, en-US, fr-FR
Layout="fr-FR"

# Run section
# Specify an executable to run
# [[Run]]
# Path="/os/HELLO.ELF"
