################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := slave
APP_SOURCES := source/slave.c

include ../../../runtime/make/exos.mk
