################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2026 Jango73
#
################################################################################

APP_NAME := pipe-upper
APP_SOURCES := source/pipe-upper.c

include ../../../runtime/make/exos.mk
