################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := netget
APP_SOURCES := source/netget.c

include ../../runtime/make/exos.mk
