
extern GetCPUID                     : near
extern DisableInterrupts            : near
extern EnableInterrupts             : near
extern LoadGlobalDescriptorTable    : near
extern LoadLocalDescriptorTable     : near
extern LoadInterruptDescriptorTable : near
extern LoadInitialTaskRegister      : near
extern PeekConsoleWord              : near
extern PokeConsoleWord              : near
extern SetConsoleCursorPosition     : near
extern MemoryCopyFromRAM            : near
extern MemoryCopyToRAM              : near
