################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2025 Jango73
#
################################################################################

APP_NAME := terminal-tactics
APP_SOURCES := \
    source/tt-ai-actions.c \
    source/tt-ai-conditions.c \
    source/tt-ai.c \
    source/tt-commands.c \
    source/tt-entities.c \
    source/tt-fog.c \
    source/tt-game.c \
    source/tt-input.c \
    source/tt-log.c \
    source/tt-main.c \
    source/tt-manual.c \
    source/tt-map.c \
    source/tt-path.c \
    source/tt-production.c \
    source/tt-render.c \
    source/tt-save.c \
    source/tt-types.c \
    source/tt-viewport.c
APP_HEADERS := $(wildcard source/*.h)

include ../../runtime/make/exos.mk
