################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2026 Jango73
#
################################################################################

APP_NAME := module-host
APP_SOURCES := source/module-host.c

include ../../../runtime/make/exos.mk
