################################################################################
#
#       EXOS System Programs
#       Copyright (c) 1999-2026 Jango73
#
################################################################################

APP_NAME := module-sample
APP_TYPE := module
APP_SOURCES := source/module-sample.c

include ../../../runtime/make/exos.mk
