name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [debug]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Build EXOS x86-64 UEFI ext2
        run: ./scripts/linux/build/build --arch x86-64 --fs ext2 --uefi --${{ matrix.config }} --no-images

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: exos-x86-64-uefi-${{ matrix.config }}
          path: |
            build/
            log/
          retention-days: 5
